Pull workflow_id and namespace into Workflow metadata for better logging
coinbase/temporal-ruby pull request #108
Opened 2021-10-15 21:09 UTC by drewhoskins-stripe

# Description
Unlike activities, I noticed our workflow logging didn't have access to the workflow_id or namespace, nor did the underlying context.
This will give user-defined loggers access so they can log consistency for the entire duration of a workflow.

Also
* I'm renaming workflow_run_id to run_id in the logs, as that's the canonical term used everywhere and can be used for log filter queries.  The only place it's slightly weird is in activities, but they do not have their own concept of run_id, so it should be unambiguous.
* Implementation detail: I removed a layer of indirection for creating metadata that was getting in the way.

# Test Plan
Some unit tests:
```
bundle exec rspec spec/unit/lib/temporal/metadata/workflow_spec.rb
bundle exec rspec ./spec/unit/lib/temporal/metadata_spec.rb
```
Plus the ambient integration tests
```
cd examples
# Terminal 1
./bin/worker
# Terminal 2
USE_ENCRYPTION = 1 ./bin/worker
# Terminal 3
bundle exec rspec spec/integration/
```
And manual inspection of logging.

2021-10-15 21:09 UTC, drewhoskins-stripe commented on lib/temporal/metadata.rb
> -      def generate(type, data, namespace = nil)
I removed this layer of indirection because we need to pass in different arguments depending on the type of metadata.

2021-10-16 22:02 UTC, antstorm approved these changes
I've noticed that this logic has already been implemented in Cadence SDK (https://github.com/coinbase/cadence-ruby/pull/60) and not synced with this repo. Can you please do that? I'm happy to do it myself as well, just trying to keep these repos directionally similar to make sure bigger changes can also be replicated without too much extra work

2021-10-16 22:03 UTC, antstorm requested changes
Sorry, meant to request changes, not approve

2021-11-18 00:00 UTC, drewhoskins-stripe commented
@jeffschoner-stripe is going to handle this one.

2021-11-18 00:00 UTC, closed without merging