Expose wait_for_start for child workflow execution
coinbase/temporal-ruby pull request #167
Opened 2022-03-18 18:49 UTC by arya-k

# Summary
Currently, in order to ensure child workflows behave as expected, we have to wait for temporal to send a ChildExecutionStarted history event. Since we can't do that, we've been sleeping. This PR adds a wait_for_start to child workflow execution so that we can reliably wait for Child workflows, as [indicated in Temporal's docs](https://docs.temporal.io/docs/concepts/what-is-a-child-workflow-execution)

# Testing
I ran:
```
bundle exec rspec spec/
cd examples
./bin/worker
USE_ENCRYPTION=1 ./bin/worker
bundle exec rspec spec/integration
```

I modified parent_close_workflow_spec to use this flag instead of sleep. If you disable `wait_for_start`, the test will fail nondeterministically.

2022-03-19 13:03 UTC, antstorm requested changes
@arya-k thanks for fixing this, really appreciate it 👍 Left 2 comments, please let me know if that doesn't make sense for any reason

2022-03-19 13:03 UTC, antstorm commented on lib/temporal/workflow/state_manager.rb
> +          dispatch(target, 'started', event.attributes.workflow_execution)
There seems to be an issue here — you're dispatching the event with one argument (`event.attributes.workflow_execution`), however the handler is registered without arguments. This suggests that the new behaviour isn't working properly and we need to figure out why the tests are still passing (indicating a potential flake)

2022-03-21 20:33 UTC, arya-k commented on lib/temporal/workflow/context.rb
> +        wait_for_start = options.delete(:wait_for_start)
I agree– I'll promote this behavior to always be enabled, with a comment indicating that temporal says we *must* wait for the child to get spawned.

2022-03-22 15:31 UTC, antstorm commented on lib/temporal/workflow/state_manager.rb
> +          dispatch(target, 'started', event.attributes.workflow_execution)
@arya-k hmm, interesting:

```ruby
>> proc = -> { p 'called' }
=> #<Proc:0x0000000123aa6da0 (irb):1 (lambda)>
>> proc.call('a')
(irb):1:in `block in <main>': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

I wonder if a block is handled differently. But you're right, your example works as expected and just ignores the argument

2022-03-23 15:55 UTC, merged