Rename Decision to WorkflowTask.
coinbase/temporal-ruby pull request #19
Opened 2020-10-31 11:07 UTC by robholland

2020-11-02 12:10 UTC, antstorm commented on lib/temporal.rb
> +      raise Error, 'Could not find a completed workflow_task task event' unless workflow_task_id
nit: `workflow_task task`

2020-11-02 12:16 UTC, robholland commented on lib/temporal.rb
> +      raise Error, 'Could not find a completed workflow_task task event' unless workflow_task_id
Fixed.

2020-11-02 12:21 UTC, antstorm requested changes

2020-11-02 12:21 UTC, antstorm commented on lib/temporal/workflow/context.rb
> +        workflow_task = WorkflowTask::ScheduleActivity.new(
I think this is a wrong assumption — top level `Decision` is not the same as `DecisionTask`, so therefore it does not translate to `WorkflowTask`. This should be a `Command`, which is what a "decision" was used as a synonym of

2020-11-02 12:21 UTC, antstorm commented on lib/temporal/workflow/history/event.rb
> +        # referred to as a "workflow_task" event. Not related to WorkflowTaskTask.
^ This comment explain exactly what is wrong with the rename :)

`decision_id` should be `command_id`

2020-11-04 11:04 UTC, robholland commented
Lets just scrap this, I'll file a fresh PR :)

2020-11-04 11:04 UTC, closed without merging