Adds ProtoJSON support for protobuf inputs
coinbase/temporal-ruby pull request #192
Opened 2022-09-06 18:15 UTC by stuppy

https://github.com/coinbase/temporal-ruby/issues/191

2022-09-09 15:30 UTC, antstorm requested changes

2022-09-09 16:38 UTC, stuppy reviewed
thanks!

2022-09-09 16:38 UTC, stuppy commented on lib/temporal/connection/converter/payload/proto_json.rb
> +          class InvalidPayload < RuntimeError; end
d'oh ya was going to add handling, but then noticed the JSON deserializer didn't have anything explicit so didn't follow up.  removed the error class.

2022-09-09 16:38 UTC, stuppy commented on lib/temporal/connection/converter/payload/proto_json.rb
> +            return unless data&.is_a?(Google::Protobuf::MessageExts)
👍 done

2022-09-09 16:38 UTC, stuppy commented on spec/unit/lib/temporal/connection/converter/payload/proto_json_spec.rb
> +require 'temporal/connection/converter/payload/json'
d'oh Done

2022-09-09 16:38 UTC, stuppy commented on spec/unit/lib/temporal/connection/converter/payload/proto_json_spec.rb
> +        data: 'hello world',
added comment. using `Temporal::Api::Common::V1::Payload` as the input given it's an available proto message. `to_payload` wraps it, so the result `data` is the json'd `input` w/ the metadata

2022-09-16 14:55 UTC, antstorm approved these changes
Looks good, thank you for the PR

2022-09-16 14:55 UTC, antstorm commented on spec/unit/lib/temporal/connection/converter/payload/proto_json_spec.rb
> +        data: 'hello world',
Ah, I see, makes sense. It might be a bit clearer if you were to pick a proto that has nothing to do with payloads. But the comment solves this issue

2022-09-16 15:07 UTC, merged